#Admin user
admin:
  user: admin
  password: test

#Default password
default:
  password: test

#Loggin
logging:
  config: classpath:logback-spring-test.xml

#JWT config
jwt:
  token:
    secret: SecretKeyToGenerateAJSONWebTokens
    expiration: 100000000
    prefix: Bearer
    header: Authorization
    issuer:
      info: InReplay