apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: football-team-management-api-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
